### ISSUE TITLE
Broken language switching

### ISSUE THREAD

**Issue by grtcdr** [dothq/scalar#14]
Changing the language from the select at the bottom of the page doesn't actually trigger anything or reload the page and redirect to **dothq.co/es**

![image](https://user-images.githubusercontent.com/35816711/120139063-978e2b80-c1cf-11eb-94a2-c2c2a2d0e7b7.png)

- Spanish isn't fully supported either, as parts of the page are still in English.

**Comment by EnderDev** [comment]
Known.

**Comment by SandroLinux** [comment]
Working on issue

**Comment by mauro-balades** [comment]
still broken...

**Comment by kierandrewett** [comment]
Fixed.
