### ISSUE TITLE
Fix the Landing Text

### ISSUE THREAD

**Issue by tregsthedev** [dothq/scalar#18]
The landing page Text isn't easy to read.

![image](https://user-images.githubusercontent.com/21000033/122309719-ca793480-cedc-11eb-96c2-95a17e6a5068.png)

**Comment by EnderDev** [comment]
Could you explain in more detail what is hard to read?

**Comment by IamTregsthedev** [comment]
It's not easy to read, the first time you read the setence. It's the font size, font or color, in the background.

You get distracted after The Browswer

**Comment by kierandrewett** [comment]
Closing as this isn't a problem anymore.
